// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_API_KEY'] ?? '', 
    appId: '1:985792666610:web:8c6ea0d8de2f679245e96b',
    messagingSenderId: '985792666610',
    projectId: 'mediscan-df3c6',
    authDomain: 'mediscan-df3c6.firebaseapp.com',
    storageBucket: 'mediscan-df3c6.firebasestorage.app',
    measurementId: 'G-NN04EZDNVQ',
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_API_KEY'] ?? '',
    appId: '1:985792666610:android:95e4f8f6541f279a45e96b',
    messagingSenderId: '985792666610',
    projectId: 'mediscan-df3c6',
    storageBucket: 'mediscan-df3c6.firebasestorage.app',
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_API_KEY'] ?? '',
    appId: '1:985792666610:ios:dce5ad5e37bd885545e96b',
    messagingSenderId: '985792666610',
    projectId: 'mediscan-df3c6',
    storageBucket: 'mediscan-df3c6.firebasestorage.app',
    iosBundleId: 'com.example.mediscan',
  );

  static FirebaseOptions macos = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_API_KEY'] ?? '',
    appId: '1:985792666610:ios:dce5ad5e37bd885545e96b',
    messagingSenderId: '985792666610',
    projectId: 'mediscan-df3c6',
    storageBucket: 'mediscan-df3c6.firebasestorage.app',
    iosBundleId: 'com.example.mediscan',
  );

  static FirebaseOptions windows = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_API_KEY'] ?? '',
    appId: '1:985792666610:web:031d9822e331d40745e96b',
    messagingSenderId: '985792666610',
    projectId: 'mediscan-df3c6',
    authDomain: 'mediscan-df3c6.firebaseapp.com',
    storageBucket: 'mediscan-df3c6.firebasestorage.app',
    measurementId: 'G-NYCVY1TCEK',
  );
}
